blank_issues_enabled: false
contact_links:
  - name: ðŸ’¬ Discussions
    url: https://github.com/AshutoshDash1999/nextjs-mantine-boilerplate/discussions
    about: Ask questions and discuss ideas with the community
  - name: ðŸ“š Documentation
    url: https://github.com/AshutoshDash1999/nextjs-mantine-boilerplate#readme
    about: Check our documentation for answers

